on: [push]
jobs:
  build:
    runs-on: docker
    concurrency:
      cancel-in-progress: false
    container:
      image: xn--55q89qy6p.com/soph/ci-base:latest
    strategy:
      matrix:
        flake: [schwi, emir-eins, emir-zwei, moshimoshi, yuuna]
    steps:
      - name: Copy ssh keys from secrets
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIV }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PUB }}" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519
          chmod 644 ~/.ssh/id_ed25519.pub
          echo "emir-eins.ex-machina.sophiah.gay ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHPSscREH9OS6V6uDUgtcnELGBcjTZsqJfsmdu28Q/+C" >> ~/.ssh/known_hosts
          echo "emir-eins.ex-machina.sophiah.gay ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFtAr0onV0UGLi/B2eWhwOaKSndfIFwJNC5CFQrcytG/Qc5r6fEY+vcKc+qQJVK6UOJ8nwAP2RHuW+aKOrtJomgyv2jhP0EFlUVh595QsCi2fDv71JjX3J8wqoIe9HYlUm2/egxTJ25IZS/KeWPmILiF32E6eIGT+0o91/FfMfMLs3yOZF42HzOqKN2MEzt9PsJRRIxPnGnFra2/eWQuJ/9FghbHAuP08Wb8IxLuAEASOxZVRuDjshLRfh6bQhVHCMhIzrK7HEwlcbdDj7kopAZzt0ZcZXcFy9g5HT8GnEEO1IMatPAdqkBSY/owM9ZJeORquV4rH7W4Pc0iGCE+8BfDiqb0DlpnPIg9h72BYvUzIsk5iC/hyauMOIyVtDmJyycmHy0FBtyK1zzxUmtmjCudhf2cXzOmSlrildmUtepxQOOwxnL42J2H0gc7PGhFT0p0eHj1OasQedMy9v5bdO3RDB7FVhH2VSTGMP9QJhcCL1hXVQEuX9PA9itdmDC2LJeHStMRF2kklfz5xhMP4qxQ3VqNQuDL8Ljv/Mj5wKnhjyUnszP5Cp7IBscGBsHVcVt0wEGK7iebWLLI9BbG8ITFT3jK9dF6zewIbwgoYpxiqQvvvGAYA5vrCdgkkjSzFBTimXjfShFLWMwqno9/z5V99rVR1rwBd64TVqkGP80w==" >> ~/.ssh/known_hosts
          echo "schwi.ex-machina.sophiah.gay ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKPHtJcY8q0xm/J8AkGbX+kx91zXpo8H893mUGqJblgh" >> ~/.ssh/known_hosts
          echo "schwi.ex-machina.sophiah.gay ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKPHtJcY8q0xm/J8AkGbX+kx91zXpo8H893mUGqJblgh" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - uses: https://git.muc.ccc.de/sophinya67/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 10G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0  
          purge-primary-key: never
      - uses: actions/checkout@v4
      - name: Deploy ${{ matrix.flake }}
        run: nix --extra-experimental-features "nix-command flakes" run github:serokell/deploy-rs .#${{ matrix.flake }} -- --ssh-user forgejo
