on:
  workflow_dispatch:
  push:

jobs:
  tests:
    runs-on: docker
    concurrency:
      cancel-in-progress: false
    container:
      image: xn--55q89qy6p.com/soph/ci-base:latest
    steps:
      - uses: actions/checkout@v6
      # Run checks one-by-one to conserve ram.. Thanks ai bubble 😭
      - name: Checks / Tests
        run: |
          nix --extra-experimental-features "nix-command flakes" build .#checks.x86_64-linux.formatting
                    
          if [[ -s result ]]; then
            echo "Error detected:"
            cat result
            exit 1
          fi
  build:
    runs-on: docker
    needs: tests
    concurrency:
      cancel-in-progress: false
    container:
      image: xn--55q89qy6p.com/soph/ci-base:latest
    strategy:
      matrix:
        flake: [schwi, emir-eins, emir-zwei, kiara,mococo]
    steps:
      - name: Copy ssh keys from secrets
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIV }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PUB }}" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519
          chmod 644 ~/.ssh/id_ed25519.pub
          echo "emir-eins.ex-machina.sophiah.gay ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHPSscREH9OS6V6uDUgtcnELGBcjTZsqJfsmdu28Q/+C" >> ~/.ssh/known_hosts
          echo "emir-zwei.ex-machina.sophiah.gay ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAdm/2geT7+PxYUSQeiOLGpchxaihM5Bxu88QKLZVoZT" >> ~/.ssh/known_hosts
          echo "schwi.ex-machina.sophiah.gay ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKPHtJcY8q0xm/J8AkGbX+kx91zXpo8H893mUGqJblgh" >> ~/.ssh/known_hosts
          echo "moshimoshi ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB2fTZEUoWt7cFlh3fVaD6auB+Hgt8tR1SSG/x1dhDaT" >> ~/.ssh/known_hosts
          echo "yuuna ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEsn1taHd1G7MLs5uI4tYsWgpYRA+d6/MdDhGtcOiGEt" >> ~/.ssh/known_hosts
          echo "kiara.dev.sophiah.gay ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILlNATR/R/C+caVM73rI7g+cuunXgL/mZ+ly7R2IpRa6" >> ~/.ssh/known_hosts
          echo "mococo.dev.sophiah.gay ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHS5eQ4DJ+wagB0gzQB+2U1JlONOiSQuNF/3aRdXMnN6" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - uses: actions/checkout@v6
      - if: matrix.flake != 'kiara'
        name: Build
        run: nix-shell -p nixos-rebuild-ng --run "nixos-rebuild build --flake .#${{ matrix.flake }} --max-jobs 1"
      - if: github.ref == 'refs/heads/main'
        name: Deploy
        run: nix --extra-experimental-features "nix-command flakes" run github:szlend/deploy-rs\?ref=fix-show-derivation-parsing .#${{ matrix.flake }} -- --skip-checks --ssh-opts "-6${{ matrix.flake == 'mococo' && ' -J forgejo@schwi.ex-machina.sophiah.gay' || '' }}" --ssh-user forgejo ${{ matrix.flake == 'kiara' && '--remote-build' || '' }} -- --max-jobs 1
