on: [push]
jobs:
  build:
    runs-on: docker
    concurrency:
      cancel-in-progress: false
    container:
      image: xn--55q89qy6p.com/soph/ci-base:latest
    strategy:
      matrix:
        flake: [schwi, moshimoshi]
    steps:
      - uses: actions/checkout@v4
      - name: Build-vm
        run: nix --extra-experimental-features nix-command run .#nixosConfigurations.${{ matrix.flake }}.config.system.build.vmWithDisko
